spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/pixyo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  address: 192.168.1.126
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:pixyo.p12
    key-store-password: pixyo2021
    key-alias: pixyo
    enabled: true
pixyo:
  app:
    jwtSecret: pixyoSecretKey
    jwtExpirationMs: 86400000